### ISSUE TITLE
IOS tag cloud is jumbled

### ISSUE THREAD

**Issue by bhaskar-bhowmik** [jekingohel/react-native-wordcloud#1]
The word cloud is not proper in IOS platform

![simulator_screenshot_79A885BE-A3E1-41E4-8C32-FA6B65BFCEE3](https://github.com/user-attachments/assets/27cf4fc9-94b0-4407-8744-a7cc1bc08e87)

version used     "rn-wordcloud": "^1.0.3",
code blocked 
<WordCloud
            options={{
              words: words,
              verticalEnabled: true,
              minFont: 10,
              maxFont: 50,
              fontOffset: 1,
              width: 350,
              height: 550,
              fontFamily: 'Arial',
              press: () => {
                console.log('===key===key==');
              },
            }}
          />

**Comment by jekingohel** [comment]
@bhaskar-bhowmik 
Ensure the WordCloud component is properly initialized with default dimensions and configuration before dynamically fetching words from a server or API. Once the words are fetched, pass them to the options.words array to update the WordCloud.
